# Generated by Django 5.2.4 on 2025-07-15 19:51

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('flower', models.AutoField(primary_key=True, serialize=False)),
                ('flower_name', models.CharField(max_length=255)),
                ('flower_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
            options={
                'ordering': ['flower_name'],
            },
        ),
        migrations.CreateModel(
            name='Fableseed',
            fields=[
                ('seed', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=130)),
                ('body', models.CharField(max_length=255)),
                ('approval_status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('fablebuds_earnt', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('flower_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nursery.flower')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
