# Generated by Django 5.2.4 on 2025-07-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0002_alter_fableseed_fablebuds_earnt_fablebranch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fablebranch',
            options={'verbose_name': 'Fablebranch', 'verbose_name_plural': 'Fablebranches'},
        ),
    ]
