# Generated by Django 5.2.4 on 2025-07-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0004_alter_fablebranch_author_alter_fableseed_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fableseed',
            name='approval_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved')], default=0),
        ),
    ]
