# Generated by Django 5.2.4 on 2025-07-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0005_alter_fableseed_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fablebranch',
            name='fablebuds_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
