# Generated by Django 5.2.4 on 2025-08-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0007_alter_fablebranch_author_alter_fablebranch_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fablebranch',
            name='fablebuds_cost',
        ),
        migrations.AddField(
            model_name='flower',
            name='fablebuds_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
