# Generated by Django 5.2.4 on 2025-09-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0008_remove_fablebranch_fablebuds_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fableseed',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
