# Generated by Django 5.2.4 on 2025-07-21 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nursery', '0004_alter_fablebranch_author_alter_fableseed_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('earned_on', models.DateTimeField(auto_now_add=True)),
                ('earned_from_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nursery.fablebranch')),
                ('earned_from_seed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nursery.fableseed')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nursery.flower')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['flower'],
            },
        ),
    ]
