# Generated by Django 5.2.4 on 2025-08-26 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_alter_userprofile_profile_picture'),
        ('nursery', '0008_remove_fablebranch_fablebuds_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userflower',
            name='earned_from_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='nursery.fablebranch'),
        ),
        migrations.AlterField(
            model_name='userflower',
            name='earned_from_seed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursery.fableseed'),
        ),
    ]
