# Generated by Django 5.2.4 on 2025-09-13 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_alter_userflower_earned_from_branch_and_more'),
        ('nursery', '0008_remove_fablebranch_fablebuds_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userflower',
            name='earned_from_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward', to='nursery.fablebranch'),
        ),
    ]
